# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'homeWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QTableView,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 720)
        icon = QIcon()
        icon.addFile(u"kiwi_logo.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 10, 1261, 681))
        self.canAnalyser = QWidget()
        self.canAnalyser.setObjectName(u"canAnalyser")
        self.canAnalyseTable = QTableView(self.canAnalyser)
        self.canAnalyseTable.setObjectName(u"canAnalyseTable")
        self.canAnalyseTable.setGeometry(QRect(10, 10, 1241, 631))
        self.tabWidget.addTab(self.canAnalyser, "")
        self.canTransmit = QWidget()
        self.canTransmit.setObjectName(u"canTransmit")
        self.idBox = QLineEdit(self.canTransmit)
        self.idBox.setObjectName(u"idBox")
        self.idBox.setGeometry(QRect(60, 50, 81, 24))
        self.lengthBox = QLineEdit(self.canTransmit)
        self.lengthBox.setObjectName(u"lengthBox")
        self.lengthBox.setGeometry(QRect(220, 50, 113, 24))
        self.msgBox = QLineEdit(self.canTransmit)
        self.msgBox.setObjectName(u"msgBox")
        self.msgBox.setGeometry(QRect(430, 50, 113, 24))
        self.idLabel = QLabel(self.canTransmit)
        self.idLabel.setObjectName(u"idLabel")
        self.idLabel.setGeometry(QRect(30, 50, 21, 21))
        self.lengthLabel = QLabel(self.canTransmit)
        self.lengthLabel.setObjectName(u"lengthLabel")
        self.lengthLabel.setGeometry(QRect(170, 50, 51, 21))
        self.msgLabel = QLabel(self.canTransmit)
        self.msgLabel.setObjectName(u"msgLabel")
        self.msgLabel.setGeometry(QRect(360, 50, 51, 21))
        self.RepeatLabel = QLabel(self.canTransmit)
        self.RepeatLabel.setObjectName(u"RepeatLabel")
        self.RepeatLabel.setGeometry(QRect(560, 50, 61, 21))
        self.repeatMsg = QCheckBox(self.canTransmit)
        self.repeatMsg.setObjectName(u"repeatMsg")
        self.repeatMsg.setGeometry(QRect(630, 50, 16, 22))
        self.periodBox = QLineEdit(self.canTransmit)
        self.periodBox.setObjectName(u"periodBox")
        self.periodBox.setEnabled(False)
        self.periodBox.setGeometry(QRect(740, 50, 113, 24))
        self.periodLabel = QLabel(self.canTransmit)
        self.periodLabel.setObjectName(u"periodLabel")
        self.periodLabel.setGeometry(QRect(670, 50, 51, 21))
        self.periodLabel.setTextFormat(Qt.AutoText)
        self.sendCANFrame = QPushButton(self.canTransmit)
        self.sendCANFrame.setObjectName(u"sendCANFrame")
        self.sendCANFrame.setGeometry(QRect(880, 50, 241, 24))
        self.DescText = QLabel(self.canTransmit)
        self.DescText.setObjectName(u"DescText")
        self.DescText.setGeometry(QRect(20, 10, 301, 31))
        self.DescText.setTextFormat(Qt.AutoText)
        self.canTransmitTable = QTableView(self.canTransmit)
        self.canTransmitTable.setObjectName(u"canTransmitTable")
        self.canTransmitTable.setGeometry(QRect(20, 80, 1221, 561))
        self.tabWidget.addTab(self.canTransmit, "")
        self.canLogger = QWidget()
        self.canLogger.setObjectName(u"canLogger")
        self.tabWidget.addTab(self.canLogger, "")
        self.canPlayback = QWidget()
        self.canPlayback.setObjectName(u"canPlayback")
        self.tabWidget.addTab(self.canPlayback, "")
        self.settings = QWidget()
        self.settings.setObjectName(u"settings")
        self.comReload = QPushButton(self.settings)
        self.comReload.setObjectName(u"comReload")
        self.comReload.setGeometry(QRect(40, 90, 80, 24))
        self.comSelect = QComboBox(self.settings)
        self.comSelect.setObjectName(u"comSelect")
        self.comSelect.setGeometry(QRect(230, 90, 311, 24))
        self.baudSelect = QComboBox(self.settings)
        self.baudSelect.addItem("")
        self.baudSelect.addItem("")
        self.baudSelect.addItem("")
        self.baudSelect.addItem("")
        self.baudSelect.addItem("")
        self.baudSelect.addItem("")
        self.baudSelect.addItem("")
        self.baudSelect.addItem("")
        self.baudSelect.addItem("")
        self.baudSelect.setObjectName(u"baudSelect")
        self.baudSelect.setGeometry(QRect(650, 90, 201, 24))
        self.label = QLabel(self.settings)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(130, 90, 91, 21))
        self.label_2 = QLabel(self.settings)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(550, 90, 91, 21))
        self.connectBtn = QPushButton(self.settings)
        self.connectBtn.setObjectName(u"connectBtn")
        self.connectBtn.setGeometry(QRect(870, 90, 80, 24))
        self.tabWidget.addTab(self.settings, "")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(800, 11, 461, 20))
        font = QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(Qt.RightToLeft)
        self.label_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(4)
        self.baudSelect.setCurrentIndex(5)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Moke CANdaptor", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canAnalyser), QCoreApplication.translate("MainWindow", u"CAN Analyser", None))
        self.idBox.setText("")
        self.idLabel.setText(QCoreApplication.translate("MainWindow", u"ID:", None))
        self.lengthLabel.setText(QCoreApplication.translate("MainWindow", u"Length:", None))
        self.msgLabel.setText(QCoreApplication.translate("MainWindow", u"Message:", None))
        self.RepeatLabel.setText(QCoreApplication.translate("MainWindow", u"Repeating:", None))
        self.repeatMsg.setText("")
        self.periodLabel.setText(QCoreApplication.translate("MainWindow", u"Period", None))
        self.sendCANFrame.setText(QCoreApplication.translate("MainWindow", u"Send Message", None))
        self.DescText.setText(QCoreApplication.translate("MainWindow", u"Send CAN Frame", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canTransmit), QCoreApplication.translate("MainWindow", u"CAN Transmitter", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canLogger), QCoreApplication.translate("MainWindow", u"CAN Logging", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canPlayback), QCoreApplication.translate("MainWindow", u"CAN Playback", None))
        self.comReload.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.baudSelect.setItemText(0, QCoreApplication.translate("MainWindow", u"10 kbps", None))
        self.baudSelect.setItemText(1, QCoreApplication.translate("MainWindow", u"20 kbps", None))
        self.baudSelect.setItemText(2, QCoreApplication.translate("MainWindow", u"50 kbps", None))
        self.baudSelect.setItemText(3, QCoreApplication.translate("MainWindow", u"100 kbps", None))
        self.baudSelect.setItemText(4, QCoreApplication.translate("MainWindow", u"125 kbps", None))
        self.baudSelect.setItemText(5, QCoreApplication.translate("MainWindow", u"250 kbps", None))
        self.baudSelect.setItemText(6, QCoreApplication.translate("MainWindow", u"500 kbps", None))
        self.baudSelect.setItemText(7, QCoreApplication.translate("MainWindow", u"800 kbps", None))
        self.baudSelect.setItemText(8, QCoreApplication.translate("MainWindow", u"1 Mbps", None))

        self.baudSelect.setCurrentText(QCoreApplication.translate("MainWindow", u"250 kbps", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Select COM port:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Selet Baud Rate:", None))
        self.connectBtn.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), QCoreApplication.translate("MainWindow", u"Settings", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"CANdaptor NOT CONNECTED", None))
    # retranslateUi

